### ISSUE TITLE
Error when running docker-compose up --build

### ISSUE THREAD

**Issue by Dave-0-0** [ChoiSG/log4shell-dockerlab#1]
I am running sudo docker-compose up --build. The build fails with the following error.

Step 4/9 : RUN gradle bootJar --no-daemon
 ---> Running in 6babbb1e881d

Welcome to Gradle 7.3.1!

Here are the highlights of this release:
 - Easily declare new test suites in Java projects
 - Support for Java 17
 - Support for Scala 3

For more details see https://docs.gradle.org/7.3.1/release-notes.html

To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.3.1/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 

FAILURE: Build failed with an exception.

* Where:
Build file '/home/gradle/src/build.gradle' line: 2

* What went wrong:
Plugin [id: 'org.springframework.boot', version: '2.6.1'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.springframework.boot:org.springframework.boot.gradle.plugin:2.6.1')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
ERROR: Service 'targetweb' failed to build: The command '/bin/sh -c gradle bootJar --no-daemon' returned a non-zero code: 1

Running on Ubuntu 20.04 with a fresh install of Docker and Docker-compose. 

Please advise.

**Comment by Dave-0-0** [comment]
Resolved by reinstalling Docker from here https://docs.docker.com/engine/install/ubuntu/

Previously I had done sudo apt-get install docker.io

**Comment by ChoiSG** [comment]
Glad it worked out. Also, thank you for coming back and updating the original issue with your solution - I really appreciate when people do that. I'll close the issue for now.
